project:
  type: book
execute:
  freeze: false
book:
  title: "Visualizing geospatial data in R"
  author: "Rick Dean"
  page-navigation: true
  favicon: favicon.ico
  chapters:
    - index.qmd
    - part_1.qmd
    - part_2.qmd
    - part_3.qmd
format:
  html:
    fontsize: 1.4rem
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 350px
    theme:
      light: cosmo
      dark: darkly
    toc: true
    other-links:
      - text: RcensusPkg
        href: https://github.com/deandevl/RcensusPkg
      - text: RspatialPkg
        href: https://github.com/deandevl/RspatialPkg
      - text: data.table
        href: https://cran.r-project.org/web/packages/data.table/index.html
      - text: deandevl
        href: https://github.com/deandevl
    code-links:
      - text: source
        icon: github
        href: "https://github.com/deandevl/RvisualizeGeospatial"
    fig-width: 12
    fig-height: 8
editor: visual
number-sections: false
date: last-modified
css: style.css


